### ISSUE TITLE
Lost street name

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/sorting_office#23]
See the address below:

```
Saxon Mount
Messingham Road
Scotter
Gainsborough
Lincolnshire
DN21 3UQ
```

Sorting Office parses it into:

```
SAON:
PAON: Saxon Mount
Street:
Locality: Scotter
Town: Gainsborough
Postcode: DN21 3UQ
```

Messingham Road is known, e.g. see [here](https://alpha.openaddressesuk.org/addresses?street=messingham&town=Gainsborough). Why is it dropped, then?

**Comment by cblanc** [comment]
The road exists, it's just that the road centroid is too far out from the postcode centroid

Currently, I believe sorting_office compares against the nearest street within a [~700m radius](https://github.com/OpenAddressesUK/sorting_office/blob/master/lib%2Fsorting_office%2Fmodels%2Fstreet.rb#L7) however according to OS Locator, the centroid for that road is ~900m away from the centroid of the `DN21 3UQ`.

So I guess the fix for this is to up the radius. 

The longer term fix might be to use the bounding box for the road provided by OS Locator and indexing and compare against that, rather than indexing the road centroids.

**Comment by giacecco** [comment]
Thanks a lot @cblanc and well spotted! @pezholio I've spoken with @murraydata and there may be some difference between the original algorithm and the implementation in Sorting Office that is causing this. Can you please check with John?
